Repository tinacms/tina.io, pull requests merged in 2020-11, with the labels that each got.

#739 chore(deps): tinacms 0.32.1
  components/inline-wysiwyg.tsx
  package.json
  yarn.lock
Labels: chore

#743 Docs: plugin typo fix
  content/docs/plugins.md
Labels: documentation

#746 fix: enterprise and home page registers forms
  pages/enterprise.tsx
  pages/index.tsx
Labels: fix

#741 docs: adds clearable to image field options
  content/docs/plugins/fields/image.md
Labels: documentation, pending-release

#742 docs: update custom toggle label field info
  content/docs/plugins/fields/toggle.md
Labels: documentation, pending-release

#751 guides: update strapi media example
  content/guides/nextjs/tina-with-strapi/authenticating-with-strapi.md
  content/guides/nextjs/tina-with-strapi/front-end-setup.md
Labels: guide

#753 docs: update useForm loading state info
  content/docs/getting-started/backends.md
  content/docs/plugins/forms.md
Labels: documentation, pending-release
