Repository tinacms/tina.io, pull requests merged in 2020-05, with the labels that each got.

#402 guides: update vercel hosting steps to reflect current process
  content/guides/nextjs/github-open-authoring/hosting-vercel.md
Labels: documentation

#408 fix: s/Jeol/Joel
  content/blog/2020-05-04-release-notes.md
Labels: blog

#412 Update nextjs blog
  content/blog/simple-markdown-blog-nextjs.md
  content/blog/using-tinacms-with-nextjs.md
  content/guides/nextjs/github-open-authoring/initial-setup.md
Labels: blog, guide

#415 blog: remove 'src' subdir references
  content/blog/using-tinacms-with-nextjs.md
Labels: blog

#420 Update from TinaCMS
  content/docs/inline-editing/inline-image.md
Labels: documentation

#417 Update plugin docs to reflect module syntax and async plugin registration
  content/docs/cms/plugins.md
Labels: documentation, pending-release

#424 docs: adds tags field docs
  content/docs/fields/select.md
  content/docs/fields/tags.md
  content/toc-doc.json
  public/img/fields/tags-field.png
Labels: documentation, pending-release

#436 fix: updated inline-wysiwyg docs
  content/docs/inline-editing/inline-wysiwyg.md
Labels: documentation
