Repository tinacms/tina.io, pull requests merged in 2020-06, with the labels that each got.

#433 Blocks & Inline docs updates
  content/docs/fields/html.md
  content/docs/inline-blocks/block-image.md
  content/docs/inline-blocks/block-text.md
  content/docs/inline-blocks/block-textarea.md
  content/docs/inline-editing.md
  content/docs/inline-editing/inline-blocks.md
  content/docs/inline-editing/inline-group.md
  content/docs/inline-editing/inline-image.md
  content/docs/inline-editing/inline-text.md
  content/docs/inline-editing/inline-textarea.md
  content/docs/inline-editing/inline-wysiwyg.md
  content/toc-doc.json
  now.json
Labels: documentation, pending-release

#385 Adds Next-Git Guide & General Next.js package docs
  content/blog/deprecating-tina-git-server.md
  content/blog/using-tinacms-with-nextjs.md
  content/docs/forms.md
  content/docs/media.md
  content/docs/nextjs/bootstrapping.md
  content/docs/nextjs/creating-forms.md
  content/docs/nextjs/next-tinacms-github.md
  content/docs/nextjs/next-tinacms-json.md
  content/docs/nextjs/next-tinacms-markdown.md
  content/docs/nextjs/overview.md
  content/guides/nextjs/git-based/adding-backend.md
  content/guides/nextjs/git-based/creating-git-forms.md
  content/guides/nextjs/git-based/getting-started.md
  content/guides/nextjs/git-based/meta.json
  content/toc-doc.json
  now.json
Labels: documentation, guide

#442 docs: updates inline group docs with latest changes
  content/docs/inline-editing/inline-group.md
Labels: documentation

#460 Adds docs for new placeholder prop on SidebarState
  content/docs/cms.md
Labels: documentation, pending-release

#477 docs: update GitHub OAuth with Vercel screenshot
  public/img/github-open-auth-cna/oauth-with-vercel.png
Labels: documentation

#474 Update to guide for new auth flow
  content/guides/nextjs/github-open-authoring/github-oauth-app.md
Labels: guide

#469 The New Github Auth Flow Blog Post
  content/blog/upgrade-notice-improved-github-security.md
Labels: blog

#496 Date Field Extraction Docs
  content/docs/fields/date.md
Labels: documentation

#471 Adds inline editing guide
  content/docs/inline-editing/inline-image.md
  content/guides/general/inline-blocks/add-more-blocks.md
  content/guides/general/inline-blocks/customize-controls.md
  content/guides/general/inline-blocks/extend-styles.md
  content/guides/general/inline-blocks/hero-to-block.md
  content/guides/general/inline-blocks/inline-form-fields.md
  content/guides/general/inline-blocks/meta.json
  content/guides/general/inline-blocks/nested-blocks.md
  content/guides/general/inline-blocks/overview.md
  content/guides/general/inline-blocks/settings-modal.md
  content/guides/general/inline-blocks/wrap-up.md
  public/img/inline-editing-guide/add-more-blocks-step.png
  public/img/inline-editing-guide/border-radius-x-y.png
  public/img/inline-editing-guide/feature-list.png
  public/img/inline-editing-guide/hero-to-block.png
  public/img/inline-editing-guide/images-block.jpg
  public/img/inline-editing-guide/paragraph-block.png
  public/img/inline-editing-guide/settings-modal.png
  public/img/inline-editing-guide/step1-install.png
  public/img/inline-editing-guide/step4-inline-fields.png
  public/img/inline-editing-guide/step9-focus-ring.png
Labels: guide

#502 docs: blocks limits
  content/docs/inline-editing/inline-blocks.md
  content/docs/inline-editing/inline-image.md
  content/guides/general/inline-blocks/add-more-blocks.md
  content/guides/general/inline-blocks/customize-controls.md
  content/guides/general/inline-blocks/extend-styles.md
  content/guides/general/inline-blocks/hero-to-block.md
  content/guides/general/inline-blocks/inline-form-fields.md
  content/guides/general/inline-blocks/meta.json
  content/guides/general/inline-blocks/nested-blocks.md
  content/guides/general/inline-blocks/overview.md
  content/guides/general/inline-blocks/settings-modal.md
  content/guides/general/inline-blocks/wrap-up.md
  public/img/inline-editing-guide/add-more-blocks-step.png
  public/img/inline-editing-guide/border-radius-x-y.png
  public/img/inline-editing-guide/feature-list.png
  public/img/inline-editing-guide/hero-to-block.png
  public/img/inline-editing-guide/images-block.jpg
  public/img/inline-editing-guide/paragraph-block.png
  public/img/inline-editing-guide/settings-modal.png
  public/img/inline-editing-guide/step1-install.png
  public/img/inline-editing-guide/step4-inline-fields.png
  public/img/inline-editing-guide/step9-focus-ring.png
Labels: documentation, pending-release

#509 guide: adds block limits example
  content/guides/general/inline-blocks/extend-styles.md
Labels: guide, pending-release
