Repository tinacms/tina.io, pull requests merged in 2020-07, with the labels that each got.

#513 Docs: update Vercel hosting
  content/guides/nextjs/github-open-authoring/hosting-vercel.md
Labels: documentation

#522 chore: update guide example
  content/guides/nextjs/github-open-authoring/toolbar-plugins.md
Labels: guide

#525 Docs: Remove duplicated words from docs, and remove hard-coded localhost urls from GitClient config docs.
  content/blog/custom-field-plugins.md
  content/blog/using-tinacms-with-nextjs.md
  content/docs/nextjs/next-tinacms-github.md
  content/guides/nextjs/git-based/adding-backend.md
  content/guides/nextjs/github-open-authoring/api-functions.md
Labels: documentation

#531 docs: Add form buttons docs
  content/docs/forms.md
Labels: documentation

#532 Remove old Inline controls info
  content/docs/inline-editing.md
Labels: documentation

#534 docs: Updates form buttons info on UI doc
  content/docs/cms.md
  content/docs/cms/ui.md
  content/docs/forms.md
Labels: documentation

#539 docs: update Inline Gatsby image children example
  content/docs/inline-editing/inline-image.md
Labels: documentation

#555 add a table listing the available plugin types to the /docs/plugins page
  content/docs/plugins.md
Labels: documentation

#557 content creator plugin docs
  content/docs/plugins/content-creators.md
Labels: documentation

#558 Docs integrations
  content/blog/gatsby-tina-101.md
  content/blog/screen-plugins.md
  content/blog/simple-markdown-blog-nextjs.md
  content/blog/three-ways-to-edit-md.md
  content/blog/using-tinacms-with-nextjs.md
  content/docs/getting-started/introduction.md
  content/docs/index.md
  content/docs/integrations/gatsby.md
  content/docs/integrations/nextjs.md
  content/docs/nextjs/next-tinacms-github.md
  content/docs/plugins/fields/group-list.md
  content/toc-doc.json
  now.json
Labels: documentation

#562 chore: fix old references to global forms
  content/blog/gatsby-tina-101.md
  content/blog/screen-plugins.md
Labels: blog

#561 guides: renames github open auth guide
  content/blog/2020-05-04-release-notes.md
  content/docs/integrations/nextjs.md
  content/docs/nextjs/next-tinacms-github.md
  content/docs/ui.md
  content/guides/nextjs/github-open-authoring/meta.json
  content/guides/nextjs/github/api-functions.md
  content/guides/nextjs/github/auth-redirect.md
  content/guides/nextjs/github/configure-custom-app.md
  content/guides/nextjs/github/custom-doc-styled-components.md
  content/guides/nextjs/github/github-forms.md
  content/guides/nextjs/github/github-oauth-app.md
  content/guides/nextjs/github/hosting-vercel.md
  content/guides/nextjs/github/initial-setup.md
  content/guides/nextjs/github/loading-github-content.md
  content/guides/nextjs/github/meta.json
  content/guides/nextjs/github/toolbar-plugins.md
  pages/guides/[category]/[guide]/[step].tsx
Labels: guide

#536 Docs & Guides TOC
  components/styles/DocsRichText.tsx
  components/styles/GlobalStyle.tsx
  components/styles/fontImports.css
  components/toc/index.tsx
  package.json
  pages/_app.tsx
  pages/blog/[slug].tsx
  pages/docs/[...slug].tsx
  pages/guides/[category]/[guide]/[step].tsx
  pages/guides/index.tsx
  utils/getMarkdownFile.ts
  yarn.lock
Labels: enhancement

#564 fix loading markdown preview props
  utils/getMarkdownFile.ts
Labels: fix

#567 Docs plugins toolbar widget
  content/docs/plugins/toolbar-widgets.md
Labels: documentation

#569 guide: updates cms.enabled at auth step to check for undefined
  content/guides/nextjs/github/configure-custom-app.md
Labels: guide

#570 Style: Update packages page layout
  components/ui/Toc.tsx
  components/ui/index.ts
  content/docs/index.md
  content/docs/plugins/toolbar-widgets.md
  pages/blog/[slug].tsx
  pages/docs/[...slug].tsx
  pages/guides/[category]/[guide]/[step].tsx
  pages/packages/[slug].tsx
Labels: style

#563 Packages Page
  components/layout/DocsLayout.tsx
  components/layout/Layout.tsx
  components/ui/Toc.tsx
  components/ui/index.ts
  content/packages.json
  content/toc-doc.json
  pages/blog/[slug].tsx
  pages/docs/[...slug].tsx
  pages/guides/[category]/[guide]/[step].tsx
  pages/packages/[slug].tsx
  pages/packages/index.tsx
  utils/docs/getPackageProps.ts
  utils/getJsonPreviewProps.ts
Labels: enhancement

#574 chore: update env example
  .env.example
Labels: chore

#577 refactors toc & adds to packages pages
  components/toc/index.tsx
  components/ui/index.ts
  pages/blog/[slug].tsx
  pages/docs/[...slug].tsx
  pages/guides/[category]/[guide]/[step].tsx
  pages/packages/[slug].tsx
  utils/docs/getPackageProps.ts
  utils/index.ts
  utils/toc_helpers.ts
Labels: enhancement, fix

#579 Deprioritize non-default fields
  content/docs/plugins/fields/blocks.md
  content/docs/plugins/fields/custom-fields.md
  content/docs/plugins/fields/date.md
  content/docs/plugins/fields/html.md
  content/docs/plugins/fields/image.md
  content/docs/plugins/fields/markdown.md
  content/docs/plugins/fields/number.md
  content/docs/plugins/fields/textarea.md
  content/toc-doc.json
Labels: documentation

#582 fix: generate better slugs in docs ToC
  utils/docs/getPackageProps.ts
  utils/docs/slugifyToc.test.ts
  utils/docs/slugifyToc.ts
  utils/getMarkdownFile.ts
Labels: fix

#591 docs: adds cms methods docs
  content/docs/cms.md
Labels: documentation
