Repository tinacms/tina.io, pull requests merged in 2020-04, with the labels that each got.

#329 Docs: Update Inline Editing
  content/blog/three-ways-to-edit-md.md
  content/docs/fields/blocks.md
  content/docs/gatsby/custom-fields.md
  content/docs/gatsby/inline-editing.md
  content/docs/inline-blocks.md
  content/docs/inline-blocks/block-image.md
  content/docs/inline-blocks/block-text.md
  content/docs/inline-blocks/block-textarea.md
  content/docs/inline-editing.md
  content/docs/inline-editing/inline-image.md
  content/docs/inline-editing/inline-text.md
  content/docs/inline-editing/inline-textarea.md
  content/docs/inline-editing/inline-wysiwyg.md
  content/docs/nextjs/inline-editing.md
  content/docs/nextjs/markdown.md
  content/toc-doc.json
  now.json
  public/_redirects
Labels: documentation

#333 Docs: Removes outdated style helper info on Custom Fields doc
  content/docs/fields/custom-fields.md
Labels: documentation

#331 blog: adds screen plugin blog post
  content/blog/screen-plugins.md
  public/img/blog/screen-plugin/fullscreen-screen-plugin.png
  public/img/blog/screen-plugin/popup-screen-plugin.png
  public/img/blog/screen-plugin/quokka-selfie-global-menu.png
  public/img/blog/screen-plugin/quokka-selfie-plugin-full.png
  public/img/blog/screen-plugin/quokka.jpg
Labels: blog

#342 Fix custom fields examples
  content/docs/fields/custom-fields.md
  content/docs/gatsby/custom-fields.md
Labels: documentation

#339 Remove useLocalForm refs
  content/docs/nextjs/creating-forms.md
Labels: documentation

#375 refactor: converts the github open-auth doc to 'guide' structure
  content/docs/nextjs/github-public-repo.md
  content/docs/nextjs/markdown.md
  content/guides/nextjs/github-open-authoring/api-functions.md
  content/guides/nextjs/github-open-authoring/auth-redirect.md
  content/guides/nextjs/github-open-authoring/configure-custom-app.md
  content/guides/nextjs/github-open-authoring/custom-doc-styled-components.md
  content/guides/nextjs/github-open-authoring/github-forms.md
  content/guides/nextjs/github-open-authoring/github-oauth-app.md
  content/guides/nextjs/github-open-authoring/hosting-vercel.md
  content/guides/nextjs/github-open-authoring/initial-setup.md
  content/guides/nextjs/github-open-authoring/loading-github-content.md
  content/guides/nextjs/github-open-authoring/meta.json
  content/guides/nextjs/github-open-authoring/toolbar-plugins.md
  content/toc-doc.json
Labels: documentation

#344 GitHub public repo docs
  content/guides/nextjs/github-open-authoring/api-functions.md
  content/guides/nextjs/github-open-authoring/auth-redirect.md
  content/guides/nextjs/github-open-authoring/configure-custom-app.md
  content/guides/nextjs/github-open-authoring/custom-doc-styled-components.md
  content/guides/nextjs/github-open-authoring/github-forms.md
  content/guides/nextjs/github-open-authoring/github-oauth-app.md
  content/guides/nextjs/github-open-authoring/hosting-vercel.md
  content/guides/nextjs/github-open-authoring/initial-setup.md
  content/guides/nextjs/github-open-authoring/loading-github-content.md
  content/guides/nextjs/github-open-authoring/meta.json
  content/guides/nextjs/github-open-authoring/toolbar-plugins.md
  content/toc-doc.json
  pages/api/create-github-access-token.ts
  public/img/github-open-auth-cna/after-auth-fork.png
  public/img/github-open-auth-cna/create-fork-step.png
  public/img/github-open-auth-cna/create-next-app-2.png
  public/img/github-open-auth-cna/create-next-app.png
  public/img/github-open-auth-cna/oAuth-app-config.png
  public/img/github-open-auth-cna/oauth-with-vercel.png
  public/img/github-open-auth-cna/toolbar-plugins.png
  public/img/github-open-auth-cna/vercel-env-vars.png
  yarn.lock
Labels: documentation

#390 Adds Editing UI docs
  content/docs/cms/ui.md
  content/toc-doc.json
Labels: documentation

#394 Adjust Docs Nav Submenu Item Font
  components/layout/DocsTextWrapper.tsx
  components/ui/DocsNav.tsx
  content/guides/index.md
  content/toc-doc.json
Labels: style
