Repository tinacms/tina.io, pull requests merged in 2020-08, with the labels that each got.

#612 Docs: Updates inline editing docs
  content/docs/plugins/fields.md
  content/docs/ui/inline-editing.md
  content/docs/ui/inline-editing/inline-blocks.md
Labels: documentation

#623 Adds Missing Comma To Object
  content/guides/nextjs/github/configure-custom-app.md
Labels: documentation

#617 Improve Nav Search
  components/search/hitComps.tsx
  indices/createIndices.ts
  utils/blog_helpers.ts
Labels: enhancement

#624 Fix typo in table of contents on gatsby guides
  content/guides/gatsby/adding-tina/next-steps.md
  content/guides/gatsby/adding-tina/project-setup.md
Labels: documentation

#616 docs: updates blocks controls interface example
  content/docs/ui/inline-editing/inline-blocks.md
Labels: documentation, pending-release

#626 docs: adds guides to docs nav
  content/toc-doc.json
Labels: documentation

#590 Tutorial: Getting started
  content/docs/getting-started/backends.md
  content/docs/getting-started/cms-set-up.md
  content/docs/getting-started/edit-content.md
  content/docs/getting-started/introduction.md
  content/docs/index.md
  content/docs/plugins/fields/custom-fields.md
  content/toc-doc.json
  public/img/getting-started/alert.png
  public/img/getting-started/cms-setup-step.png
  public/img/getting-started/edit-data.png
  public/img/getting-started/tina-tutorial-step1.png
Labels: documentation

#619 Blog Template: next / prev posts
  components/ui/BlogPagination.tsx
  content/blog/add-and-delete-files.md
  content/blog/announcing-tinacms.md
  content/blog/creating-markdown-drafts.md
  content/blog/custom-field-components.md
  content/blog/custom-field-plugins.md
  content/blog/deprecating-tina-git-server.md
  content/blog/designing-an-extensible-styling-system.md
  content/blog/dynamic-plugin-system.md
  content/blog/editing-on-the-cloud.md
  content/blog/exporting-wordpress-content-to-gatsby.md
  content/blog/gatsby-tina-101.md
  content/blog/inline-editing-project.md
  content/blog/introducing-tina-grande.md
  content/blog/introducing-visual-open-authoring.md
  content/blog/jamstack-denver-talk.md
  content/blog/screen-plugins.md
  content/blog/simple-markdown-blog-nextjs.md
  content/blog/software-engineering-daily-podcast-tinacms.md
  content/blog/three-ways-to-edit-md.md
  content/blog/tinacms-ui-whats-next.md
  content/blog/upgrade-notice-improved-github-security.md
  content/blog/using-tinacms-on-gatsby-cloud.md
  content/blog/using-tinacms-with-nextjs.md
  content/blog/what-are-blocks.md
  pages/blog/[slug].tsx
Labels: blog, enhancement

#565 Refactor to get GitHub file
  package.json
  pages/blog/[slug].tsx
  pages/blog/page/[page_index].tsx
  pages/docs/releases.tsx
  pages/guides/[category]/[guide]/[step].tsx
  pages/guides/index.tsx
  utils/docs/getDocProps.ts
  utils/getJsonPreviewProps.ts
  utils/getMarkdownPreviewProps.ts
  yarn.lock
Labels: refactor

#632 Added placeholder to list of options
  content/docs/ui/inline-editing/inline-text.md
Labels: documentation

#628 Guide Index template updates
  components/DocumentationNavigation/DocumentationNavigation.tsx
  components/DocumentationNavigation/NavSection.tsx
  content/guides/index.md
  content/toc-doc.json
  pages/guides/index.tsx
Labels: guide

#630 refactor: extract useFormDecorator from useLastEdited
  utils/useLastEdited.ts
Labels: refactor

#639 fix: redirects
  now.json
Labels: fix

#641 Fixed Docs Nav Header + Search
  components/DocumentationNavigation/DocsHeaderNav.tsx
  components/DocumentationNavigation/DocsLeftSidebar.tsx
  components/DocumentationNavigation/DocsNavigationList.tsx
  components/DocumentationNavigation/DocumentationNavigation.tsx
  components/DocumentationNavigation/NavSection.tsx
  components/search/index.tsx
  components/search/input.tsx
  components/search/styles.tsx
  content/docs-navigation.json
Labels: documentation, enhancement, guide

#636 Adds guide breadcrumb
  components/DocumentationNavigation/DocsNavigationList.tsx
  components/DocumentationNavigation/DocumentationNavigation.tsx
  components/DocumentationNavigation/NavSection.tsx
  components/DocumentationNavigation/index.tsx
  components/layout/DocsLayout.tsx
  pages/guides/[category]/[guide]/[step].tsx
Labels: enhancement, guide

#652 Nav Scroll
  components/DocumentationNavigation/DocsNavigationList.tsx
  components/DocumentationNavigation/DocumentationNavigation.tsx
  components/DocumentationNavigation/NavSection.tsx
Labels: documentation, enhancement, guide

#654 All Packages Page
  content/packages.json
  content/toc-doc.json
  pages/packages/[slug].tsx
  pages/packages/index.tsx
  utils/docs/getPackageProps.ts
Labels: enhancement

#656 docs: adds toolbar example image
  content/docs/ui.md
  public/img/toolbar-ex.jpg
Labels: documentation

#660 Remove obsolete docs
  content/docs/nextjs/next-tinacms-github.md
  content/docs/nextjs/next-tinacms-json.md
  content/docs/nextjs/next-tinacms-markdown.md
  now.json
Labels: documentation

#657 Fix rss feed
  pages/rss.xml.tsx
  utils/blog_helpers.ts
Labels: fix

#653 Guide Index Updates
  components/styles/DocsRichText.tsx
  content/docs/integrations/gatsby.md
  content/docs/integrations/nextjs.md
  content/guides/index.md
Labels: guide

#662 InlineText Updates
  content/docs/ui/inline-editing/inline-text.md
  content/docs/ui/inline-editing/inline-textarea.md
Labels: documentation

#666 Adds next / prev for FAQ
  content/docs/getting-started/backends.md
  content/docs/getting-started/faq.md
Labels: documentation

#667 Fixed release notes button
  tinacms/ReleaseNotesCreator.ts
Labels: fix

#671 fix(guides/index): send preview data to getDocsNav
  pages/guides/index.tsx
Labels: fix

#670 Adds Feedback form
  .env.example
  components/forms/FeedbackForm.tsx
  components/forms/index.ts
  components/layout/DocsLayout.tsx
  package.json
  pages/api/feedback.ts
  yarn.lock
Labels: enhancement

#675 docs: points inlinewysiwyg to react-tinacms-editor
  content/docs/media.md
  content/docs/ui/inline-editing/inline-wysiwyg.md
Labels: documentation

#679 Tiny fixes
  content/docs/index.md
  content/docs/plugins/forms.md
Labels: documentation

#683 Random Docs Updates
  content/docs/cms.md
  content/docs/plugins/forms.md
  content/docs/ui.md
Labels: documentation
