Repository tinacms/tina.io, pull requests merged in 2021-03, with the labels that each got.

#807 fix: Jamstack
  content/pages/home.json
Labels: fix

#808 fix: Homepage SEO
  content/pages/home.json
  content/siteConfig.json
Labels: fix

#793 docs: tina.io
  README.md
Labels: chore, documentation

#800 fix: broken image in production
  pages/community.tsx
Labels: fix

#799 chore: tinacms & next.js & cleanup
  .nvmrc
  components/layout/Layout.tsx
  components/ui/ActionableModal.tsx
  content/blog/tinacms-ui-whats-next.md
  content/docs/releases/2020-03-23.md
  content/docs/releases/2020-03-30.md
  content/siteConfig.json
  package.json
  pages/blog/[slug].tsx
  pages/community.tsx
  pages/docs/[...slug].tsx
  pages/early-access.tsx
  pages/github/authorizing.tsx
  pages/guides/[category]/[guide]/[step].tsx
  yarn.lock
Labels: chore

#814 Fix 404 from jamstack.org
  now.json
Labels: fix

#819 docs: TOC on setting up GitHub OAuth App
  content/guides/nextjs/github/github-oauth-app.md
Labels: documentation

#821 fix: docs navigation
  content/docs-navigation.json
  now.json
Labels: fix

#822 chore(deps): tinacms 0.39.0 + Next 10.1
  package.json
  yarn.lock
Labels: chore, dependencies

#823 Updated default branch
  content/guides/nextjs/github/github-oauth-app.md
Labels: documentation
