Repository tinacms/tina.io, pull requests merged in 2021-08, with the labels that each got.

#992 fix: Discord link
  content/docs/tina-cloud/alpha-faq.md
  content/docs/tina-cloud/beta-migration.md
  content/pages/community.json
  pages/community.tsx
Labels: fix

#1006 Tina beta launch post
  content/blog/tina-is-in-beta.md
Labels: blog

#1017 fix: 404 on /cloud
  now.json
Labels: fix

#1018 Remove unnecessary bracket in docs
  content/docs/media-cloudinary.md
Labels: documentation

#1023 docs: Tina is now in public beta
  content/blog/tina-cloud-a-headless-cms-backed-by-git.md
  content/blog/using-graphql-with-the-filesystem.md
Labels: documentation
